### ISSUE TITLE
Add a new TonelLoaderGitParentBaseEditionStrategy

### ISSUE THREAD

**Issue by marianopeck** [vasmalltalk/tonel-vast#30]
Add a new `TonelLoaderGitParentBaseEditionStrategy` (or whatever name) that rather than use "Latest" it looks into the ENVY manager if there is a version matching the parent of the current commit hash. For this we would need to investigate how to read the parent of the current commit with the file system.

**Comment by eMaringolo** [comment]
We discussed this in a meeting with Mariano, and what we want is an option to load a base edition of an Application/Subapplication that is closer to what was versioned instead of using _the latest_ one. 

E.g. You're loading `YourApplication` from Tonel sources in a git repository, and the git HEAD is at the `cf1234ab` commit hash, and its parent commit is `e2394a92`, then when looking for a base edition to load, we look for one that matches such commit hash (by means of a pattern, text-search, etc.), so we find `YourApplication master-e2394a92` edition and load that  instead of the "latest one" (which in some cases might be the same one).

**Comment by eMaringolo** [comment]
After looking and reading about the internals of git, there is no simple way to extract the parent commits of a particular commit other than to parse directly the binary files in `.git/objects/`, in some cases requiring to parse the [packfiles](https://codewords.recurse.com/issues/three/unpacking-git-packfiles).

We would need to extract the commit by calling a git command on the git repository.

So: 
 ```
$ git cat-file commit HEAD
tree 47b9dc8f9e2cc5da2c09aebf79731e6f35fa7d85
parent c3b72568c09808a298280800c38ba14e0a1c8414
author Esteban A. Maringolo  1577745693 -0300
```
