### ISSUE TITLE
./envy/Tonel.dat : Invalid Record

### ISSUE THREAD

**Issue by Noschvie** [vasmalltalk/tonel-vast#45]
Import configuration map terminates with error message below

![grafik](https://user-images.githubusercontent.com/48217146/80792848-cfbed700-8b95-11ea-92bf-b903ccc7e611.png)

**Comment by eMaringolo** [comment]
HI @Noschvie, the .dat file seemed to get corrupted on pushing/pulling to/from the repository. We changed the `.gitattributes` to treat all *.dat as binary files to avoid any issues.

We tested it with @marianopeck both in our existing images, libraries, and also in empty ones and it works.

Maybe you need to drop and clone this `tonel-vast` repository again, in order to avoid anything that could be wrong in the merge (it shouldn't, but it does not harm to clone it again).

**Comment by Noschvie** [comment]
download and import successful, thanks!

Norbert
